name: Tests CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#   schedule:
#     - cron:  '*/15 * * * *'
jobs:

  job1:
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
          with:
            repository: ismailktami/postmannewmanci
            path: postmannewmanci
      - name: Test postman
        run: cat  README.md

