name: Tests CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  SETUP:
    runs-on: ubuntu-latest
    steps:

      - name: Tests SETUP
        run: |
          echo setup

  TEST1:
    runs-on: ubuntu-latest
    needs: SETUP
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: ismailktami/postmannewmanci
          path: postmannewmanci
    # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          
      - name: Test postman
        run: cat postmannewmanci/README.md

  TEST2:
    runs-on: ubuntu-latest
    needs: [TEST1]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: ismailktami/robotframeworkdemo
          path: robotframeworkdemo

      - name: Prepare Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' 

      - name: Build Image
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get -y update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -yqq unzip
          wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_106`/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
          chmod 777 /usr/local/bin/chromedriver
          pip install --upgrade pip
          pip install requests==2.23.0
          pip install robotframework==4.1.3
          pip install robotframework-selenium2library==3.0.0
          pip install robotframework-seleniumlibrary==4.3.0
          pip install utils==1.0.1

      - name: Test Python
        run: |
         value="$(<main/datasets/dataset.json)"
         robot  tests.robot
         robot  -v dataset:$value  tests.json

  TEARDOWN:
    runs-on: ubuntu-latest
    needs: [TEST2]
    if: always()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Test Save results
        run: |
          timestamp=$(date +"%Y%m%d%H%M%S")
          mkdir -p executions
          touch DatasetPT-$timestamp.json
          cp DatasetPT-$timestamp.json  executions

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: add execution